#!/bin/bash

g++ progrev.cpp -o progrev_bin

g++ part1_simple.cpp -o part1_simple_bin

g++ part1_binary.cpp -o part1_binary_bin

g++ par2_simple.cpp -o part2_simple_bin

g++ par2_ukaz.cpp -o part2_ukaz_bin

g++ part3_A_uniform.cpp -o part3_A_uniform_bin

g++ part3_A_binom.cpp -o part3_A_binom_bin

g++ part3_B_uniform.cpp -o part3_B_uniform_bin

g++ part3_B_binom.cpp -o part3_B_binom_bin

echo "the end of compilling"

