#!/bin/bash

./progrev_bin

echo "the end of progrev"

# part 1 binary search

./part1_binary_bin > part1_binary_data.txt

echo "part1_binary_data.txt" | python graph.py

echo "the end of part 1 binary search"

# part 2 ukaz search

./part2_ukaz_bin > part2_ukaz_data.txt

echo "part2_ukaz_data.txt" | python graph.py

echo "the end of part 2 ukaz search"

echo "the fast part is over"
